mqtt:
  url: tcp://test.mosquitto.org:1883
  uniqueId: duccer
  topicPrefix: homeassistant
duc:
  url: http://foo:bar@192.168.0.0
  disallowedPrefixes:
    - 1.dm.
#    - 1.al.
    - 1.am.
intervalSeconds: 30
